LIBRARY = AnalyzerTools
OBJDIR = obj
DEPDIR = $(OBJDIR)/dep
SRCDIR = src
INCDIR = include
ADDITIONAL_ROOTMAPLIBRARY= -rml libDataFormats.so -rml libHist.so

include $(ArNeuT_WD)/makefile.common

INCLUDES += -I$(ArNeuT_WD)/DataFormats/include/
