LIBRARY = Analyzers
OBJDIR = obj
DEPDIR = $(OBJDIR)/dep
SRCDIR = src
INCDIR = include
ADDITIONAL_ROOTMAPLIBRARY = -rml libAnalyzerTools.so -rml libTree.so

include $(ArNeuT_WD)/makefile.common

INCLUDES += -I$(ArNeuT_WD)/AnalyzerTools/include/
